% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Final Project 131},
  pdfauthor={Yuanning Li},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Final Project 131}
\author{Yuanning Li}
\date{2022-11-08}

\begin{document}
\maketitle

\hypertarget{introduction}{%
\subsection{Introduction}\label{introduction}}

The aim of the project is to analyze the population trend among the
world from 1970s to 2020s, and research about which model can best fit
on the population data and predict and population. I use data from
\(Kaggle\) and implement several techniques to answer the questions
about population, growth rate, country areas, etc. I am also interested
in fitting models on current data to predict the trend.

\hypertarget{loading-packages-and-setting-up-the-environment}{%
\subsubsection{Loading Packages and Setting Up The
Environment}\label{loading-packages-and-setting-up-the-environment}}

This project uses data from \(Kaggle\) which records the population,
land area, population density, etc. of 234 countries.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)   }\CommentTok{\# using tidyverse and tidymodels for this project mostly}
\FunctionTok{library}\NormalTok{(tidymodels)}
\FunctionTok{library}\NormalTok{(ggplot2)   }\CommentTok{\# for most of our visualizations}
\FunctionTok{library}\NormalTok{(rpart.plot)  }\CommentTok{\# for visualizing trees}
\FunctionTok{library}\NormalTok{(randomForest)   }\CommentTok{\# for building our randomForest}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# import data}
\NormalTok{df }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{\textquotesingle{}data/world\_population.csv\textquotesingle{}}\NormalTok{)}
\FunctionTok{head}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Rank CCA3 Country.Territory          Capital Continent X2022.Population
## 1   36  AFG       Afghanistan            Kabul      Asia         41128771
## 2  138  ALB           Albania           Tirana    Europe          2842321
## 3   34  DZA           Algeria          Algiers    Africa         44903225
## 4  213  ASM    American Samoa        Pago Pago   Oceania            44273
## 5  203  AND           Andorra Andorra la Vella    Europe            79824
## 6   42  AGO            Angola           Luanda    Africa         35588987
##   X2020.Population X2015.Population X2010.Population X2000.Population
## 1         38972230         33753499         28189672         19542982
## 2          2866849          2882481          2913399          3182021
## 3         43451666         39543154         35856344         30774621
## 4            46189            51368            54849            58230
## 5            77700            71746            71519            66097
## 6         33428485         28127721         23364185         16394062
##   X1990.Population X1980.Population X1970.Population Area..km..
## 1         10694796         12486631         10752971     652230
## 2          3295066          2941651          2324731      28748
## 3         25518074         18739378         13795915    2381741
## 4            47818            32886            27075        199
## 5            53569            35611            19860        468
## 6         11828638          8330047          6029700    1246700
##   Density..per.km.. Growth.Rate World.Population.Percentage
## 1           63.0587      1.0257                        0.52
## 2           98.8702      0.9957                        0.04
## 3           18.8531      1.0164                        0.56
## 4          222.4774      0.9831                        0.00
## 5          170.5641      1.0100                        0.00
## 6           28.5466      1.0315                        0.45
\end{verbatim}

\hypertarget{data-description}{%
\subsubsection{DATA DESCRIPTION}\label{data-description}}

This database from \(Kaggle\) contains 17 variables and 234 columns.
While the codebook is provided in my text file, the variables listed
here are useful for understanding this report.

\texttt{Rank}=``Rank of Popluation''

\texttt{CCA3}=``3 Digit Country/Territories Code''

\texttt{Country}=``Name of the Country/ Territories''

\texttt{Capital}=``Name of the Capital''

\texttt{Continent}=``Name of the Continent''

\texttt{2022\_Population}=``Population of the Country/Territories in the
year 2022''

\texttt{2020\_Population}=``Population of the Country/Territories in the
year 2020''

\texttt{2015\_Population}=``Population of the Country/Territories in the
year 2015''

\texttt{2010\_Population}=``Population of the Country/Territories in the
year 2010''

\texttt{2000.Population}=``Population of the Country/Territories in the
year 2000''

\texttt{1990\_Population}=``Population of the Country/Territories in the
year 1990''

\texttt{1980\_Population}=``Population of the Country/Territories in the
year 1980''

\texttt{1970\_Population}=``Population of the Country/Territories in the
year 1970''

\texttt{Area}=``Area size of the Country/Territories in square
kilometer''

\texttt{Density}=``Population Density per square kilometer''

\texttt{Growth\_Rate}=``Population Growth Rate by Country/Territories''

\texttt{World\_Population\_Percentage}=``The Population percentage by
each Country/Territories''

Note: a full copy of the codebook is available in text files

\hypertarget{what-is-the-current-state-of-the-world-population}{%
\subsubsection{What is the current state of the world
population?}\label{what-is-the-current-state-of-the-world-population}}

In June 2019, the world population estimate surveyed by the U.S. Census
Bureau showed that the current global population is 757,713,040 people,
which is much higher than the world population of 7.2 billion in 2015.
It seems that the earth is very crowded and the population is still
growing very fast.

\hypertarget{why-is-analyzing-and-modeling-the-population-so-important}{%
\subsubsection{Why is analyzing and modeling the population so
important?}\label{why-is-analyzing-and-modeling-the-population-so-important}}

For a growing population, since the resources on our planet are limited,
the more the population, the greater the demand for various resources.
When the world's population reaches a certain number, resources will be
exhausted, and the loss of resources may lead to the destruction of the
earth! So I hope these analysis and models can help us understand the
current population situation and take corresponding measures to maintain
the earth.

\hypertarget{project-pathway}{%
\subsubsection{Project pathway}\label{project-pathway}}

Knowing the background and the importance of the topic, I'd like to
discuss how to analyze and build models. First I do some initial data
manipulation and cleaning on the original data. Then I explore the data
and see if there's any interesting findings about population, density,
area in time series and continent perspective.

At the end, I use existing data from previous years to make the
prediction. I'll split and resample the data, build the recipe and
workflow, and train the model. Because this is a regression problem, I
choose Ridge regression, Lasso regression, regression tree, and random
forest these four models. I'd like to find the best parameters for our
model using cross validation, and find which of the four models perform
the best on our test dataset.

\hypertarget{clean-data}{%
\subsubsection{Clean Data}\label{clean-data}}

Our original data is quite clean, so there's not much data cleaning to
do. I simply renamed the feature names to make it more clean.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# renamed all of the columns to make column names more clean and neat}
\FunctionTok{colnames}\NormalTok{(df) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Rank\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}CCA3\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Capital\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Continent\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_2022\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}Population\_2020\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_2010\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}Population\_2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_1990\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_1980\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}Population\_1970\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Area\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Density\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Growth\_Rate\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}World\_Population\_Percentage\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{exploratory-data-analysis-eda}{%
\subsection{Exploratory Data Analysis
(EDA)}\label{exploratory-data-analysis-eda}}

The entire exploratory data analysis will be based on the entire data
set with 234 observations. Each observation represents the data of a
country.

\hypertarget{key-takeaways}{%
\subsubsection{Key Takeaways}\label{key-takeaways}}

\hypertarget{what-are-the-countries-with-largest-and-smallest-population-in-the-world-is-china-going-to-remain-the-top-1-population-country-in-the-world-in-the-future}{%
\subparagraph{-- What are the countries with largest and smallest
population in the world? Is China going to remain the Top 1 population
country in the world in the
future?}\label{what-are-the-countries-with-largest-and-smallest-population-in-the-world-is-china-going-to-remain-the-top-1-population-country-in-the-world-in-the-future}}

\hypertarget{are-the-countries-with-small-density-population-has-smaller-growth-rate-than-those-countries-with-large-density-population}{%
\subparagraph{-- Are the countries with small density / population has
smaller growth rate than those countries with large density /
population?}\label{are-the-countries-with-small-density-population-has-smaller-growth-rate-than-those-countries-with-large-density-population}}

\hypertarget{in-the-continent-perspective-which-continent-has-largest-population-and-density-what-is-the-trend}{%
\subparagraph{-- In the continent perspective, which continent has
largest population and density? What is the
trend?}\label{in-the-continent-perspective-which-continent-has-largest-population-and-density-what-is-the-trend}}

\hypertarget{what-are-the-largest-and-smallest-countries-in-size}{%
\subparagraph{-- What are the largest and smallest countries in
size?}\label{what-are-the-largest-and-smallest-countries-in-size}}

The EDA part will answer the above questions.

First extract the top five countries by population from 1970 to 2022.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# for EDA, no need for more dropping or cleaning, we will clean later for model}
\CommentTok{\# add column for growth rate??}
\CommentTok{\# EDA}
\CommentTok{\# 1. Top 5 populous countries in 1970, 1980, 1990, 2000, 2010, 2015, 2020 and 2022.}
\NormalTok{df1 }\OtherTok{\textless{}{-}}\NormalTok{ df}
\FunctionTok{colnames}\NormalTok{(df1) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Rank\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}CCA3\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Capital\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Continent\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Area\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Density\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Growth\_Rate\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}World\_Population\_Percentage\textquotesingle{}}\NormalTok{)}

\NormalTok{df1 }\OtherTok{\textless{}{-}}\NormalTok{ df1 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}
                       \StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols=}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}
                       \StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{),}
                      \AttributeTok{names\_to =} \StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{\textquotesingle{}Population\textquotesingle{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(Population)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(Year) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{)}
\FunctionTok{head}\NormalTok{(df1, }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 3
## # Groups:   Year [2]
##    Country       Year  Population
##    <chr>         <chr>      <int>
##  1 China         1970   822534450
##  2 India         1970   557501301
##  3 United States 1970   200328340
##  4 Russia        1970   130093010
##  5 Indonesia     1970   115228394
##  6 China         1980   982372466
##  7 India         1980   696828385
##  8 United States 1980   223140018
##  9 Indonesia     1980   148177096
## 10 Russia        1980   138257420
\end{verbatim}

Then, use the above content to make a bar plot. it show the population
of the top five populous countries from 1970 to 2022.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{Country, }\AttributeTok{y=}\NormalTok{Population, }\AttributeTok{x=}\NormalTok{Year)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position=}\StringTok{\textquotesingle{}dodge\textquotesingle{}}\NormalTok{, }\AttributeTok{stat=}\StringTok{\textquotesingle{}identity\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{ (}\StringTok{\textquotesingle{}Top 5 Populous Countries from 1970 to 2022\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-5-1.pdf}

From the figure, We can conclude that Russia's population growth is
relatively small, so that it fell out of the top five after 1990. Brazil
had a large population in 1990-2010, and it was not in the top five at
other times. China has always maintained the first place, but India's
population has grown relatively faster and has been catching up with
China. In the very near future, India's population will soon catch up
with China's.

Then, we extract the least five countries by population from 1970 to
2022.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 2. Top 5 populous countries in 1970, 1980, 1990, 2000, 2010, 2015, 2020 and 2022.}
\NormalTok{df2 }\OtherTok{\textless{}{-}}\NormalTok{ df}
\FunctionTok{colnames}\NormalTok{(df2) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Rank\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}CCA3\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Capital\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Continent\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Area\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Density\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Growth\_Rate\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}World\_Population\_Percentage\textquotesingle{}}\NormalTok{)}

\NormalTok{df2 }\OtherTok{\textless{}{-}}\NormalTok{ df2 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}
                       \StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols=}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}
                       \StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{),}
                      \AttributeTok{names\_to =} \StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{\textquotesingle{}Population\textquotesingle{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(Population) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(Year) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{)}
\FunctionTok{head}\NormalTok{(df2, }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 3
## # Groups:   Year [2]
##    Country          Year  Population
##    <chr>            <chr>      <int>
##  1 Vatican City     1970         752
##  2 Tokelau          1970        1714
##  3 Falkland Islands 1970        2274
##  4 Saint Barthelemy 1970        2417
##  5 Niue             1970        5185
##  6 Vatican City     1980         733
##  7 Tokelau          1980        1647
##  8 Falkland Islands 1980        2240
##  9 Saint Barthelemy 1980        2983
## 10 Niue             1980        3637
\end{verbatim}

The method I use to create a bar plot is similar to the previous
question, it shows the population of the five least populous countries
from 1970 to 2022.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df2, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{Country, }\AttributeTok{y=}\NormalTok{Population, }\AttributeTok{x=}\NormalTok{Year)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{position=}\StringTok{\textquotesingle{}dodge\textquotesingle{}}\NormalTok{, }\AttributeTok{stat=}\StringTok{\textquotesingle{}identity\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{ (}\StringTok{\textquotesingle{}Top 5 Least Populous Countries from 1970 to 2022\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-7-1.pdf}

We can conclude that the population of Niue began to decrease from 1970
until 2010, and then increased a little. Montserrat is gaining momentum,
starting in 2000 as the most populous of the five least populated
countries, but Falkland Island has been growing as well.

Next, we look at the population growth rate for top 5 countries.

As described above, although China's population is currently the largest
in the world, India is gaining momentum. Is it possible to surpass China
and become the next country with the largest population in the world?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 3. growth rate of the 5 most populous countries}
\NormalTok{df3 }\OtherTok{\textless{}{-}}\NormalTok{ df1 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(Year }\SpecialCharTok{==} \DecValTok{2022}\NormalTok{)}
\NormalTok{df\_tmp }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Growth\_Rate\textquotesingle{}}\NormalTok{))}
\NormalTok{df3 }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(df3, df\_tmp, }\AttributeTok{by=}\StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{, }\AttributeTok{all.x=}\ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Growth\_Rate\textquotesingle{}}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(Population))}
\NormalTok{df3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Country Population Growth_Rate
## 1         China 1425887337      1.0000
## 2         India 1417173173      1.0068
## 3 United States  338289857      1.0038
## 4     Indonesia  275501339      1.0064
## 5      Pakistan  235824862      1.0191
\end{verbatim}

From the data, the China has the least population growth rate and
Pakistan has the highest population growth rate. Based on India's growth
rate of 1.0068 is higher than China's growth rate of 1.0000, and the
population until 2022, we expect India's population will have more than
China's population.

Using the data \texttt{df3} obtained above, make a visualization to
observe the population and growth trends of the top five countries in
the world.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df3, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\FunctionTok{reorder}\NormalTok{(Country, }\SpecialCharTok{+}\FunctionTok{desc}\NormalTok{(Population))))  }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Population}\SpecialCharTok{*}\FloatTok{0.000000001}\NormalTok{, }\AttributeTok{group=}\DecValTok{1}\NormalTok{),}\AttributeTok{stat=}\StringTok{"identity"}\NormalTok{, }\AttributeTok{fill=}\StringTok{"cyan"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{(Growth\_Rate}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\AttributeTok{group=}\DecValTok{1}\NormalTok{),}\AttributeTok{stat=}\StringTok{"identity"}\NormalTok{,}\AttributeTok{color=}\StringTok{"black"}\NormalTok{,}\AttributeTok{size=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{name =} \StringTok{\textquotesingle{}Population in Billion\textquotesingle{}}\NormalTok{, }\AttributeTok{sec.axis=}\FunctionTok{sec\_axis}\NormalTok{(}\AttributeTok{trans =} \SpecialCharTok{\textasciitilde{}}\NormalTok{.}\SpecialCharTok{*}\DecValTok{1}\NormalTok{, }\AttributeTok{name=}\StringTok{"Increase Growth Rate in percent"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=} \StringTok{"Population vs. Growth Rate Top 5 Populous Countries"}\NormalTok{, }\AttributeTok{x =} \StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{(Growth\_Rate}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\AttributeTok{group=}\DecValTok{1}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\AttributeTok{x=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{), }\AttributeTok{y =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\FloatTok{0.8}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\FloatTok{0.8}\NormalTok{, }\FloatTok{1.7}\NormalTok{), }\AttributeTok{label=}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.68}\NormalTok{, }\FloatTok{0.38}\NormalTok{, }\FloatTok{0.64}\NormalTok{, }\FloatTok{1.91}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## i Please use `linewidth` instead.
\end{verbatim}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-9-1.pdf}

To better visualize the growth rate, we changed population growth rate
to increase of growth rate in percentage,for example, India's growth
rate is 1.0068, so the increase of growth rate is 0.68\%.

From the plot, Pakistan has the highest increase of growth rate 1.91\%.
China has a increase of growth rate 0\% in recent years, while India has
a increase of growth rate 0.68\%. If maintains, India's population will
surpass that of China.

Then, we look at the comparison of population density. First look at the
five countries with the lowest population density.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 4. The 5 countries with the least population density}
\NormalTok{df4 }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(Density) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Country"}\NormalTok{,}\StringTok{"Population\_2022"}\NormalTok{, }\StringTok{"Density"}\NormalTok{))}
\NormalTok{df4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            Country Population_2022 Density
## 1        Greenland           56466  0.0261
## 2 Falkland Islands            3780  0.3105
## 3   Western Sahara          575986  2.1654
## 4         Mongolia         3398366  2.1727
## 5          Namibia         2567012  3.1092
\end{verbatim}

From the data, we know Greenland, Falkland Islands, Western Sahara,
Mongolia and Namibia has the least population density.

Using the data \texttt{df4} obtained above, make a visualization to
observe the population and density of the five countries with the least
population in the world.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df4, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\FunctionTok{reorder}\NormalTok{(Country, }\SpecialCharTok{+}\NormalTok{Population\_2022)))  }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Population\_2022}\SpecialCharTok{*}\FloatTok{0.000001}\NormalTok{, }\AttributeTok{group=}\DecValTok{1}\NormalTok{),}\AttributeTok{stat=}\StringTok{"identity"}\NormalTok{, }\AttributeTok{fill=}\StringTok{"blue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Density, }\AttributeTok{group=}\DecValTok{1}\NormalTok{),}\AttributeTok{stat=}\StringTok{"identity"}\NormalTok{,}\AttributeTok{color=}\StringTok{"black"}\NormalTok{,}\AttributeTok{size=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{name =} \StringTok{\textquotesingle{}Population in Million\textquotesingle{}}\NormalTok{, }\AttributeTok{sec.axis=}\FunctionTok{sec\_axis}\NormalTok{(}\AttributeTok{trans =} \SpecialCharTok{\textasciitilde{}}\NormalTok{.}\SpecialCharTok{*}\DecValTok{1}\NormalTok{, }\AttributeTok{name=}\StringTok{"Density (per km\^{}2)"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=} \StringTok{"5 Least Density Countries"}\NormalTok{, }\AttributeTok{x=} \StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Density, }\AttributeTok{group=}\DecValTok{1}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\AttributeTok{x=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{), }\AttributeTok{y =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.51}\NormalTok{,}\FloatTok{0.23}\NormalTok{,}\FloatTok{2.36}\NormalTok{,}\FloatTok{3.31}\NormalTok{,}\FloatTok{2.37}\NormalTok{), }\AttributeTok{label=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.31}\NormalTok{,}\FloatTok{0.03}\NormalTok{,}\FloatTok{2.16}\NormalTok{,}\FloatTok{3.11}\NormalTok{,}\FloatTok{2.17}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-11-1.pdf}

From the figure, the blue bars represents the population and the line
represents the population density. Of the five countries, Namibia has
the highest population density of 3.11\((people/km^2)\) and Greenland
has the lowest of 0.03\((people/km^2)\).

Next, we look at the population growth rate for 5 countries with least
density.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Growth rate of the 5 least densely populated countries}
\NormalTok{df5 }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(Density) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Country"}\NormalTok{, }\StringTok{"Density"}\NormalTok{, }\StringTok{"Growth\_Rate"}\NormalTok{))}
\NormalTok{df5}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            Country Density Growth_Rate
## 1        Greenland  0.0261      1.0040
## 2 Falkland Islands  0.3105      1.0043
## 3   Western Sahara  2.1654      1.0184
## 4         Mongolia  2.1727      1.0151
## 5          Namibia  3.1092      1.0146
\end{verbatim}

From the data, the Greenland has the least population growth rate and
Western Sahara has the highest population growth rate.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df5, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\FunctionTok{reorder}\NormalTok{(Country, }\SpecialCharTok{+}\NormalTok{Density)))  }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Density, }\AttributeTok{group=}\DecValTok{1}\NormalTok{),}\AttributeTok{stat=}\StringTok{"identity"}\NormalTok{, }\AttributeTok{fill=}\StringTok{"orange"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{(Growth\_Rate}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\AttributeTok{group=}\DecValTok{1}\NormalTok{),}\AttributeTok{stat=}\StringTok{"identity"}\NormalTok{,}\AttributeTok{color=}\StringTok{"black"}\NormalTok{,}\AttributeTok{size=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{name =} \StringTok{\textquotesingle{}Density (per km\^{}2)\textquotesingle{}}\NormalTok{, }\AttributeTok{sec.axis=}\FunctionTok{sec\_axis}\NormalTok{(}\AttributeTok{trans =} \SpecialCharTok{\textasciitilde{}}\NormalTok{.}\SpecialCharTok{*}\DecValTok{1}\NormalTok{, }\AttributeTok{name=}\StringTok{"Increase Growth Rate in percent"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=} \StringTok{"5 Least Density Countries\textquotesingle{}s Growth Rate"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Country"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{(Growth\_Rate}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{, }\AttributeTok{group=}\DecValTok{1}\NormalTok{), }\AttributeTok{col=}\StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\AttributeTok{x=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{), }\AttributeTok{y =} \FunctionTok{c}\NormalTok{(}\FloatTok{0.6}\NormalTok{,}\FloatTok{0.6}\NormalTok{,}\DecValTok{2}\NormalTok{,}\FloatTok{1.7}\NormalTok{,}\FloatTok{1.7}\NormalTok{), }\AttributeTok{label=}\FunctionTok{c}\NormalTok{(}\FloatTok{0.4}\NormalTok{,}\FloatTok{0.43}\NormalTok{,}\FloatTok{1.81}\NormalTok{,}\FloatTok{1.51}\NormalTok{,}\FloatTok{1.46}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-13-1.pdf}

From the plot, the Western Sahara has the highest increase population
growth rate of 1.81\%, and the Greenland has the lowest increase
population growth rate of 0.4\%. comparing to the countries with large
population and high density, the increase of growth rate of these low
density countries are the similar.

Then, Let's focus on the proportion of the population of different
continents in the world from 1970 to 2022.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 6. Population distribution by continent}
\NormalTok{df6 }\OtherTok{\textless{}{-}}\NormalTok{ df}

\NormalTok{df6 }\OtherTok{\textless{}{-}}\NormalTok{ df6 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Continent\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_2022\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_2020\textquotesingle{}}\NormalTok{,}
                       \StringTok{\textquotesingle{}Population\_2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_2010\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}Population\_2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_1990\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}Population\_1980\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_1970\textquotesingle{}}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(Continent) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{sum\_2022 =} \FunctionTok{sum}\NormalTok{(Population\_2022),}
            \AttributeTok{sum\_2020 =} \FunctionTok{sum}\NormalTok{(Population\_2020),}
            \AttributeTok{sum\_2015 =} \FunctionTok{sum}\NormalTok{(Population\_2015),}
            \AttributeTok{sum\_2010 =} \FunctionTok{sum}\NormalTok{(Population\_2010),}
            \AttributeTok{sum\_2000 =} \FunctionTok{sum}\NormalTok{(Population\_2000),}
            \AttributeTok{sum\_1990 =} \FunctionTok{sum}\NormalTok{(Population\_1990),}
            \AttributeTok{sum\_1980 =} \FunctionTok{sum}\NormalTok{(Population\_1980),}
            \AttributeTok{sum\_1970 =} \FunctionTok{sum}\NormalTok{(Population\_1970))}

\FunctionTok{colnames}\NormalTok{(df6) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Continent\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{)}

\NormalTok{df6 }\OtherTok{\textless{}{-}}\NormalTok{ df6 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols=}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}
                       \StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{),}
                      \AttributeTok{names\_to =} \StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{\textquotesingle{}Population\textquotesingle{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(Continent, Year)}
\NormalTok{df6[[}\StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{]] }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(df6[[}\StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{]])}
\end{Highlighting}
\end{Shaded}

This time we use a line chart to do this visualization.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ df6, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Year)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Population }\SpecialCharTok{/} \DecValTok{1000000000}\NormalTok{, }\AttributeTok{colour=}\NormalTok{Continent)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Population }\SpecialCharTok{/} \DecValTok{1000000000}\NormalTok{, }\AttributeTok{colour=}\NormalTok{Continent)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=} \StringTok{"Population distribution by Continent"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Population in Billion"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-15-1.pdf}

In the plot,Asia's population grows fast continuously form 1970s to
2022. And its population is much more than other continents.The other
continent that has obvious population growth trend is Africa. Compare to
Asia and Africa, other continents do not have a big growth throughout
the years. The population of Oceania is the smallest of all continents,
and the growth rate is also very small.

Then, Let's look at the population density of each of these continents.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 7. Population density of each continent}

\NormalTok{df7 }\OtherTok{\textless{}{-}}\NormalTok{ df}

\NormalTok{df7 }\OtherTok{\textless{}{-}}\NormalTok{ df7 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Continent\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_2022\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_2020\textquotesingle{}}\NormalTok{,}
                       \StringTok{\textquotesingle{}Population\_2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_2010\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}Population\_2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_1990\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}Population\_1980\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}Population\_1970\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Area\textquotesingle{}}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(Continent) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{density\_2022 =} \FunctionTok{sum}\NormalTok{(Population\_2022) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Area),}
            \AttributeTok{density\_2020 =} \FunctionTok{sum}\NormalTok{(Population\_2020) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Area),}
            \AttributeTok{density\_2015 =} \FunctionTok{sum}\NormalTok{(Population\_2015) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Area),}
            \AttributeTok{density\_2010 =} \FunctionTok{sum}\NormalTok{(Population\_2010) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Area),}
            \AttributeTok{density\_2000 =} \FunctionTok{sum}\NormalTok{(Population\_2000) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Area),}
            \AttributeTok{density\_1990 =} \FunctionTok{sum}\NormalTok{(Population\_1990) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Area),}
            \AttributeTok{density\_1980 =} \FunctionTok{sum}\NormalTok{(Population\_1980) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Area),}
            \AttributeTok{density\_1970 =} \FunctionTok{sum}\NormalTok{(Population\_1970) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(Area))}

\FunctionTok{colnames}\NormalTok{(df7) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}Continent\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}
                  \StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{)}

\NormalTok{df7 }\OtherTok{\textless{}{-}}\NormalTok{ df7 }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pivot\_longer}\NormalTok{(}\AttributeTok{cols=}\FunctionTok{c}\NormalTok{(}\StringTok{\textquotesingle{}2022\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2020\textquotesingle{}}\NormalTok{,}
                       \StringTok{\textquotesingle{}2015\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}2010\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}2000\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1990\textquotesingle{}}\NormalTok{,}
                      \StringTok{\textquotesingle{}1980\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}1970\textquotesingle{}}\NormalTok{),}
                      \AttributeTok{names\_to =} \StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{, }\AttributeTok{values\_to =} \StringTok{\textquotesingle{}Density\textquotesingle{}}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(Continent, Year)}
\NormalTok{df7[[}\StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{]] }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(df7[[}\StringTok{\textquotesingle{}Year\textquotesingle{}}\NormalTok{]])}
\end{Highlighting}
\end{Shaded}

Through the above calculation and classification, visualization can now
be made.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ df7, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{Year)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_line}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Density, }\AttributeTok{colour=}\NormalTok{Continent)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Density, }\AttributeTok{colour=}\NormalTok{Continent)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=} \StringTok{"Population Density by Continent"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Density per km\^{}2"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-17-1.pdf}

From the visualization, Asia is still far ahead of other continents.
From a population density of about 65 people per square kilometer in
1970 to about 150 people per square kilometer in 2022. Oceania still has
the lowest population density. In 1970, the population density was about
1 to 2 people per square kilometer. By 2022, about 3 to 4 people per
square kilometer.

By comparing population trend and population density trend from 1970 to
2020, we find the two trend shares the same pattern.

Finally, we are interest in the land area of countries. The following
distribution is the largest 5 countries and the smallest 5 countries.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Five largest countries}
\NormalTok{df8 }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(Area)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Country"}\NormalTok{, }\StringTok{"Area"}\NormalTok{))}
\NormalTok{df8}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         Country     Area
## 1        Russia 17098242
## 2        Canada  9984670
## 3         China  9706961
## 4 United States  9372610
## 5        Brazil  8515767
\end{verbatim}

The Largest country is Russia, the Area is 17098242 \(km^2\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df8, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\FunctionTok{reorder}\NormalTok{(Country, }\SpecialCharTok{+}\FunctionTok{desc}\NormalTok{(Area))))  }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Area}\SpecialCharTok{/}\DecValTok{1000000}\NormalTok{, }\AttributeTok{group=}\DecValTok{1}\NormalTok{),}\AttributeTok{stat=}\StringTok{"identity"}\NormalTok{, }\AttributeTok{fill=}\StringTok{"purple"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\AttributeTok{x=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{), }\AttributeTok{y =} \FunctionTok{c}\NormalTok{(}\FloatTok{16.098}\NormalTok{,}\FloatTok{10.985}\NormalTok{,}\FloatTok{10.707}\NormalTok{,}\FloatTok{10.373}\NormalTok{,}\FloatTok{9.516}\NormalTok{), }\AttributeTok{label=}\FunctionTok{c}\NormalTok{(}\FloatTok{17.098}\NormalTok{,}\FloatTok{9.985}\NormalTok{,}\FloatTok{9.707}\NormalTok{,}\FloatTok{9.373}\NormalTok{,}\FloatTok{8.516}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=} \StringTok{"Five Largest Countries"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Area in Million km\^{}2"}\NormalTok{, }
        \AttributeTok{x =} \StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-19-1.pdf}

In the visualization, Russia is shown to have the largest area, roughly
twice the size of Brazil, which ranks fifth. The area gap between
Canada, China and the United States, which ranks second to fourth, is
relatively small.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Five smallest countries}
\NormalTok{df9 }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(Area) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Country"}\NormalTok{, }\StringTok{"Area"}\NormalTok{))}
\NormalTok{df9}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        Country Area
## 1 Vatican City    1
## 2       Monaco    2
## 3    Gibraltar    6
## 4      Tokelau   12
## 5        Nauru   21
\end{verbatim}

The smallest country is Vatican City, and it's area is 1\(km^2\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(df9, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\FunctionTok{reorder}\NormalTok{(Country, }\SpecialCharTok{+}\NormalTok{Area)))  }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y=}\NormalTok{Area, }\AttributeTok{group=}\DecValTok{1}\NormalTok{),}\AttributeTok{stat=}\StringTok{"identity"}\NormalTok{, }\AttributeTok{fill=}\StringTok{"brown"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\AttributeTok{x=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{), }\AttributeTok{y =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{13}\NormalTok{,}\DecValTok{20}\NormalTok{), }\AttributeTok{label=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{12}\NormalTok{,}\DecValTok{21}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title=} \StringTok{"Five Smallest Countries"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Area in Million km\^{}2"}\NormalTok{, }
        \AttributeTok{x =} \StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-21-1.pdf}

In the visualization, the Vatican is shown to have the smallest area at
1\(km^2\), about the size of a square. The largest of them, Nauru, is
only 21\(km^2\).

\hypertarget{data-split-cross-validation}{%
\subsection{Data split \& cross
validation}\label{data-split-cross-validation}}

For model training, we only keep the relevant features, including all
the previous year's population, area, and continent. We delete features
such as density and growth rate because they can be used to calculate
population of 2022 directly (correlation is almost 1).

The data was split in 70\% training, 30\% testing split. Stratified
sampling was used as the \texttt{Continent}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# keep only the relevant variables}
\NormalTok{data }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(Continent, Area, Population\_1970, }
\NormalTok{                        Population\_1980, Population\_1990, Population\_2000,}
\NormalTok{                        Population\_2010, Population\_2015, Population\_2020,}
\NormalTok{                        Population\_2022))}
\FunctionTok{head}\NormalTok{(data) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Continent    Area Population_1970 Population_1980 Population_1990
## 1      Asia  652230        10752971        12486631        10694796
## 2    Europe   28748         2324731         2941651         3295066
## 3    Africa 2381741        13795915        18739378        25518074
## 4   Oceania     199           27075           32886           47818
## 5    Europe     468           19860           35611           53569
## 6    Africa 1246700         6029700         8330047        11828638
##   Population_2000 Population_2010 Population_2015 Population_2020
## 1        19542982        28189672        33753499        38972230
## 2         3182021         2913399         2882481         2866849
## 3        30774621        35856344        39543154        43451666
## 4           58230           54849           51368           46189
## 5           66097           71519           71746           77700
## 6        16394062        23364185        28127721        33428485
##   Population_2022
## 1        41128771
## 2         2842321
## 3        44903225
## 4           44273
## 5           79824
## 6        35588987
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# initial train test split}
\NormalTok{pop\_split }\OtherTok{\textless{}{-}} \FunctionTok{initial\_split}\NormalTok{(data, }\AttributeTok{strata =}\NormalTok{ Continent, }\AttributeTok{prop =} \FloatTok{0.7}\NormalTok{)}
\NormalTok{pop\_split}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## <Training/Testing/Total>
## <162/72/234>
\end{verbatim}

The training data set has 161 observations and the testing data set has
73 observations.

Then we use the cross validation resampling method to fold the training
data into 10 folds with 5 repeats.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pop\_train }\OtherTok{\textless{}{-}} \FunctionTok{training}\NormalTok{(pop\_split)}
\NormalTok{pop\_test }\OtherTok{\textless{}{-}} \FunctionTok{testing}\NormalTok{(pop\_split)}
\CommentTok{\# 5 fold cross validation}
\NormalTok{pop\_folds }\OtherTok{\textless{}{-}} \FunctionTok{vfold\_cv}\NormalTok{(pop\_train, }\AttributeTok{v =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{model-building}{%
\subsection{Model Building}\label{model-building}}

Steps we use to build and analysis the model:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Build the recipe and workflow for each of the model.
\item
  Use cross validation to tune the model parameters, and find the best
  parameter for the model.
\item
  Use the best parameters found in step2, fit the model on test set and
  calculate model performance.
\item
  Compare the performance for each model. Find the best model in the
  four models.
\end{enumerate}

\hypertarget{building-the-recipe}{%
\subsubsection{Building the Recipe}\label{building-the-recipe}}

set up preprocess recipe for all models.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{recipe }\OtherTok{\textless{}{-}} 
  \FunctionTok{recipe}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ Population\_2022 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ pop\_train) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{step\_novel}\NormalTok{(}\FunctionTok{all\_nominal\_predictors}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{step\_dummy}\NormalTok{(}\FunctionTok{all\_nominal\_predictors}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{step\_zv}\NormalTok{(}\FunctionTok{all\_predictors}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{step\_normalize}\NormalTok{(}\FunctionTok{all\_predictors}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

After many considerations, I decided to build the following four models.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Ridge Regression
\item
  Lasso Regression
\item
  Regression Tree
\item
  Random Forest
\end{enumerate}

\hypertarget{ridge-regression}{%
\subsubsection{Ridge Regression}\label{ridge-regression}}

Loaded the required object that I saved in my script, set \texttt{mode}
to \texttt{"regression"},tuned \texttt{penality}, and used the
\texttt{glmnet} engine. I stored this model and \texttt{recipe} in
workflow.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{1234}\NormalTok{)}
\NormalTok{ridge\_spec }\OtherTok{\textless{}{-}} \FunctionTok{linear\_reg}\NormalTok{(}\AttributeTok{mixture =} \DecValTok{0}\NormalTok{, }\AttributeTok{penalty =} \FunctionTok{tune}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{set\_mode}\NormalTok{(}\StringTok{"regression"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{set\_engine}\NormalTok{(}\StringTok{"glmnet"}\NormalTok{)}

\NormalTok{ridge\_workflow }\OtherTok{\textless{}{-}} \FunctionTok{workflow}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{add\_recipe}\NormalTok{(recipe) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{add\_model}\NormalTok{(ridge\_spec)}
\end{Highlighting}
\end{Shaded}

Next, I set up the adjustment grid and updated the penalty parameters. I
tune the penalty, in the range of \(-10\) to \(10\) with the level
\(50\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ridge\_penalty\_grid }\OtherTok{\textless{}{-}} \FunctionTok{grid\_regular}\NormalTok{(}\FunctionTok{penalty}\NormalTok{(}\AttributeTok{range =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{10}\NormalTok{, }\DecValTok{10}\NormalTok{)), }\AttributeTok{levels =} \DecValTok{50}\NormalTok{)}

\NormalTok{ridge\_tune\_res }\OtherTok{\textless{}{-}} \FunctionTok{tune\_grid}\NormalTok{(}
\NormalTok{  ridge\_workflow,}
  \AttributeTok{resamples =}\NormalTok{ pop\_folds, }
  \AttributeTok{grid =}\NormalTok{ ridge\_penalty\_grid)}
\end{Highlighting}
\end{Shaded}

\hypertarget{lasso-regression}{%
\subsubsection{Lasso Regression}\label{lasso-regression}}

In a similar process, I set the model with tuning parameter penalty. Set
the engine as glmnet and created a workflow.

The difference between Lasso Regression and Ridge Regression is Lasso
regression 's mixture parameter equals 1 and Ridge regression's mixture
parameter equals 0. This differs the two models from \(L1\) to \(L2\).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{1234}\NormalTok{)}
\NormalTok{lasso\_spec }\OtherTok{\textless{}{-}} 
  \FunctionTok{linear\_reg}\NormalTok{(}\AttributeTok{penalty =} \FunctionTok{tune}\NormalTok{(), }\AttributeTok{mixture =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{set\_mode}\NormalTok{(}\StringTok{"regression"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{set\_engine}\NormalTok{(}\StringTok{"glmnet"}\NormalTok{) }

\NormalTok{lasso\_workflow }\OtherTok{\textless{}{-}} \FunctionTok{workflow}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{add\_recipe}\NormalTok{(recipe) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{add\_model}\NormalTok{(lasso\_spec)}
\end{Highlighting}
\end{Shaded}

Next, set up the adjustment grid and updated the parameters. Tune the
penalty, in the range of \(-10\) to \(10\) with the level \(50\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_penalty\_grid }\OtherTok{\textless{}{-}} \FunctionTok{grid\_regular}\NormalTok{(}\FunctionTok{penalty}\NormalTok{(}\AttributeTok{range =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{10}\NormalTok{, }\DecValTok{10}\NormalTok{)), }\AttributeTok{levels =} \DecValTok{50}\NormalTok{)}

\NormalTok{lasso\_tune\_res }\OtherTok{\textless{}{-}} \FunctionTok{tune\_grid}\NormalTok{(}
\NormalTok{  ridge\_workflow,}
  \AttributeTok{resamples =}\NormalTok{ pop\_folds, }
  \AttributeTok{grid =}\NormalTok{ lasso\_penalty\_grid)}
\end{Highlighting}
\end{Shaded}

\hypertarget{regression-tree}{%
\subsubsection{Regression Tree}\label{regression-tree}}

In this process, Set \texttt{mode} to \texttt{"regression"} and used the
\texttt{rpart} engine. Stored this model and \texttt{recipe} in
workflow.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{1234}\NormalTok{)}
\NormalTok{reg\_tree\_spec }\OtherTok{\textless{}{-}} \FunctionTok{decision\_tree}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{set\_engine}\NormalTok{(}\StringTok{"rpart"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{set\_mode}\NormalTok{(}\StringTok{"regression"}\NormalTok{)}

\NormalTok{reg\_tree\_wf }\OtherTok{\textless{}{-}} \FunctionTok{workflow}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{add\_recipe}\NormalTok{(recipe) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{add\_model}\NormalTok{(reg\_tree\_spec }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{set\_args}\NormalTok{(}\AttributeTok{cost\_complexity =} \FunctionTok{tune}\NormalTok{()))}
\end{Highlighting}
\end{Shaded}

As above, Set up the adjustment grid and updated the parameters. Tune
the cost complexity, in the range of -10 to -1 with the level 50.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reg\_tree\_param\_grid }\OtherTok{\textless{}{-}} \FunctionTok{grid\_regular}\NormalTok{(}\FunctionTok{cost\_complexity}\NormalTok{(}\AttributeTok{range =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{10}\NormalTok{, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)), }\AttributeTok{levels =} \DecValTok{50}\NormalTok{)}

\NormalTok{reg\_tree\_tune\_res }\OtherTok{\textless{}{-}} \FunctionTok{tune\_grid}\NormalTok{(}
\NormalTok{  reg\_tree\_wf, }
  \AttributeTok{resamples =}\NormalTok{ pop\_folds, }
  \AttributeTok{grid =}\NormalTok{ reg\_tree\_param\_grid}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ! Fold4: internal: A correlation computation is required, but `estimate` is constant and ha...
\end{verbatim}

\hypertarget{random-forest}{%
\subsubsection{Random Forest}\label{random-forest}}

To prepare, load the required objects that I saved in my script, tuned
\texttt{mtry}, where \texttt{mtry} is the number of levels of the trees.
Set mode to \texttt{"regression"} , and used the random Forest engine.
Stored this model and my recipe in a workflow.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{1234}\NormalTok{)}
\NormalTok{rf\_spec }\OtherTok{\textless{}{-}} \FunctionTok{rand\_forest}\NormalTok{(}\AttributeTok{mtry =} \FunctionTok{tune}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{set\_engine}\NormalTok{(}\StringTok{"randomForest"}\NormalTok{, }\AttributeTok{importance =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{set\_mode}\NormalTok{(}\StringTok{"regression"}\NormalTok{)}

\NormalTok{rf\_wf }\OtherTok{\textless{}{-}} \FunctionTok{workflow}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{add\_recipe}\NormalTok{(recipe) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{add\_model}\NormalTok{(rf\_spec)}
\end{Highlighting}
\end{Shaded}

Next, set up the tuning grid, and updated the parameters to tune the
number of level of the trees. The minimum number of level is 1 and the
maximum number of level is 9.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rf\_grid }\OtherTok{\textless{}{-}} \FunctionTok{grid\_regular}\NormalTok{(}\FunctionTok{parameters}\NormalTok{(rf\_spec) }\SpecialCharTok{\%\textgreater{}\%}
 \FunctionTok{update}\NormalTok{(}\AttributeTok{mtry =} \FunctionTok{mtry}\NormalTok{(}\AttributeTok{range=} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{9}\NormalTok{))), }\AttributeTok{levels =} \DecValTok{9}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: `parameters.model_spec()` was deprecated in tune 0.1.6.9003.
## i Please use `hardhat::extract_parameter_set_dials()` instead.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rf\_tune\_res }\OtherTok{\textless{}{-}} \FunctionTok{tune\_grid}\NormalTok{(}
\NormalTok{  rf\_wf, }
  \AttributeTok{resamples =}\NormalTok{ pop\_folds, }
  \AttributeTok{grid =}\NormalTok{ rf\_grid}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{repeated-cross-validation-parameter-tuning}{%
\subsubsection{Repeated Cross Validation Parameter
Tuning}\label{repeated-cross-validation-parameter-tuning}}

\hypertarget{ridge-regression-1}{%
\subsubsection{Ridge Regression}\label{ridge-regression-1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{autoplot}\NormalTok{(ridge\_tune\_res)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-34-1.pdf}

Use the \texttt{autoplot()}, we can observe the change of rmse and rsq
when I tune the penalty of the ridge model. From the plot, we can see
the rmse is small and stable, and rsq is large and stable at the
beginning and has a sudden drop of rmse and sudden rise of rsq at the
final. Therefore we pick the initial value as the best penalty value for
the model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ridge\_best }\OtherTok{\textless{}{-}} \FunctionTok{select\_best}\NormalTok{(ridge\_tune\_res, }\AttributeTok{metric =} \StringTok{"rsq"}\NormalTok{)}
\NormalTok{ridge\_best}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##        penalty .config              
##          <dbl> <chr>                
## 1 0.0000000001 Preprocessor1_Model01
\end{verbatim}

Using the \texttt{select\_best()} function, the best value of penalty is
1e-10.

\hypertarget{lasso-regression-1}{%
\subsubsection{Lasso Regression}\label{lasso-regression-1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{autoplot}\NormalTok{(lasso\_tune\_res)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-36-1.pdf}

The trend of this graph is similar to the one above.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_best }\OtherTok{\textless{}{-}} \FunctionTok{select\_best}\NormalTok{(lasso\_tune\_res, }\AttributeTok{metric =} \StringTok{"rsq"}\NormalTok{)}
\NormalTok{lasso\_best}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##        penalty .config              
##          <dbl> <chr>                
## 1 0.0000000001 Preprocessor1_Model01
\end{verbatim}

Also using the \texttt{select\_best()} function, the best value of
penalty is 1e-10.

\hypertarget{regression-tree-1}{%
\subsubsection{Regression Tree}\label{regression-tree-1}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{autoplot}\NormalTok{(reg\_tree\_tune\_res)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-38-1.pdf}

For regression tree model, we tune the cost complexity parameter. From
the plot, similar to ridge and lasso regression models, we can see the
rmse is small and stable, and rsq is large and stable at the beginning
and has a sudden drop of rmse and sudden rise of rsq at the final.
Therefore we also pick the initial value as the best penalty value for
the model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reg\_tree\_best }\OtherTok{\textless{}{-}} \FunctionTok{select\_best}\NormalTok{(reg\_tree\_tune\_res, }\AttributeTok{metric =} \StringTok{"rmse"}\NormalTok{)}
\NormalTok{reg\_tree\_best}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##   cost_complexity .config              
##             <dbl> <chr>                
## 1   0.00000000295 Preprocessor1_Model09
\end{verbatim}

As same before, using the \texttt{select\_best()} function, the best
value of cost complexity is 1e-10.

\hypertarget{random-forest-1}{%
\subsubsection{Random Forest}\label{random-forest-1}}

The autoplot shows when the number of levels of tree increase, the rmse
decrease and the rsq increase. However, the best value of rmse appears
at level 5 and best value of rsq appears at level 5.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{autoplot}\NormalTok{(rf\_tune\_res)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final_project_report_files/figure-latex/unnamed-chunk-40-1.pdf}

From the \texttt{autoplot()} we see the trend of rmse and rsq is getting
better when we add layer to the trees. The best value of rmse and rsq
appear when number of levels of trees is about 5.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rf\_best }\OtherTok{\textless{}{-}} \FunctionTok{select\_best}\NormalTok{(rf\_tune\_res, }\AttributeTok{metric =} \StringTok{"rmse"}\NormalTok{)}
\NormalTok{rf\_best}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 2
##    mtry .config             
##   <int> <chr>               
## 1     4 Preprocessor1_Model4
\end{verbatim}

Using the \texttt{show\_best()} function, the best value of number of
trees is config is 5 with \(mtry = 5\).

\hypertarget{model-performance-evaluation-and-select-best-model}{%
\subsection{Model performance evaluation and select best
model}\label{model-performance-evaluation-and-select-best-model}}

Create a workflow with an adjusted name so I can identify it. Use the
\(fit()\) function for each model to run the models on the test set and
find the best model by comparing r squared value.

\hypertarget{final-ridge-regression-model}{%
\subsubsection{Final Ridge Regression
Model}\label{final-ridge-regression-model}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ridge\_final }\OtherTok{\textless{}{-}} \FunctionTok{finalize\_workflow}\NormalTok{(ridge\_workflow, ridge\_best)}
\NormalTok{ridge\_final\_fit }\OtherTok{\textless{}{-}} \FunctionTok{fit}\NormalTok{(ridge\_final, }\AttributeTok{data =}\NormalTok{ pop\_train)}
\FunctionTok{augment}\NormalTok{(ridge\_final\_fit, }\AttributeTok{new\_data =}\NormalTok{ pop\_test) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rsq}\NormalTok{(}\AttributeTok{truth =}\NormalTok{ Population\_2022, }\AttributeTok{estimate =}\NormalTok{ .pred)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   <chr>   <chr>          <dbl>
## 1 rsq     standard       0.978
\end{verbatim}

\hypertarget{final-lasso-regression-model}{%
\subsubsection{Final Lasso Regression
Model}\label{final-lasso-regression-model}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_final }\OtherTok{\textless{}{-}} \FunctionTok{finalize\_workflow}\NormalTok{(lasso\_workflow, lasso\_best)}
\NormalTok{lasso\_final\_fit }\OtherTok{\textless{}{-}} \FunctionTok{fit}\NormalTok{(lasso\_final, }\AttributeTok{data =}\NormalTok{ pop\_train)}
\FunctionTok{augment}\NormalTok{(lasso\_final\_fit, }\AttributeTok{new\_data =}\NormalTok{ pop\_test) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rsq}\NormalTok{(}\AttributeTok{truth =}\NormalTok{ Population\_2022, }\AttributeTok{estimate =}\NormalTok{ .pred)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   <chr>   <chr>          <dbl>
## 1 rsq     standard       0.999
\end{verbatim}

\hypertarget{final-regression-tree-model}{%
\subsubsection{Final Regression Tree
Model}\label{final-regression-tree-model}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{reg\_tree\_final }\OtherTok{\textless{}{-}} \FunctionTok{finalize\_workflow}\NormalTok{(reg\_tree\_wf, reg\_tree\_best)}
\NormalTok{reg\_tree\_final\_fit }\OtherTok{\textless{}{-}} \FunctionTok{fit}\NormalTok{(reg\_tree\_final, }\AttributeTok{data =}\NormalTok{ pop\_train)}
\CommentTok{\#reg\_tree\_final\_fit \%\textgreater{}\%}
  \CommentTok{\#extract\_fit\_engine() \%\textgreater{}\%}
  \CommentTok{\#rpart.plot()}
\FunctionTok{augment}\NormalTok{(reg\_tree\_final\_fit, }\AttributeTok{new\_data =}\NormalTok{ pop\_test) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rsq}\NormalTok{(}\AttributeTok{truth =}\NormalTok{ Population\_2022, }\AttributeTok{estimate =}\NormalTok{ .pred)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   <chr>   <chr>          <dbl>
## 1 rsq     standard       0.801
\end{verbatim}

\hypertarget{final-random-forest-model}{%
\subsubsection{Final Random Forest
Model}\label{final-random-forest-model}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rf\_final }\OtherTok{\textless{}{-}} \FunctionTok{finalize\_workflow}\NormalTok{(rf\_wf, rf\_best)}
\NormalTok{rf\_final\_fit }\OtherTok{\textless{}{-}} \FunctionTok{fit}\NormalTok{(rf\_final, }\AttributeTok{data =}\NormalTok{ pop\_train)}
\FunctionTok{augment}\NormalTok{(rf\_final\_fit, }\AttributeTok{new\_data =}\NormalTok{ pop\_test) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{rsq}\NormalTok{(}\AttributeTok{truth =}\NormalTok{ Population\_2022, }\AttributeTok{estimate =}\NormalTok{ .pred)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   <chr>   <chr>          <dbl>
## 1 rsq     standard       0.949
\end{verbatim}

By comparison, Lasso Regression is the best model because it's r squared
value is the largest.

\hypertarget{final-model-fitting-and-analysis}{%
\subsection{Final model fitting and
analysis}\label{final-model-fitting-and-analysis}}

Compare the predictions of the four models across countries, actual
values, and append them into a data frame for comparison.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# append country, actual value, predict result from 4 models together in one data frame}
\NormalTok{data\_pred\_result }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\StringTok{\textquotesingle{}Country\textquotesingle{}}\NormalTok{, }\StringTok{\textquotesingle{}Population\_2022\textquotesingle{}}\NormalTok{)}

\NormalTok{data\_pred\_result[}\StringTok{\textquotesingle{}reg\_tree\_pred\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \FunctionTok{augment}\NormalTok{(reg\_tree\_final\_fit, }\AttributeTok{new\_data =}\NormalTok{ data)[}\StringTok{\textquotesingle{}.pred\textquotesingle{}}\NormalTok{]}

\NormalTok{data\_pred\_result[}\StringTok{\textquotesingle{}rf\_pred\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \FunctionTok{augment}\NormalTok{(rf\_final\_fit, }\AttributeTok{new\_data =}\NormalTok{ data)[}\StringTok{\textquotesingle{}.pred\textquotesingle{}}\NormalTok{]}

\NormalTok{data\_pred\_result[}\StringTok{\textquotesingle{}ridge\_pred\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \FunctionTok{augment}\NormalTok{(ridge\_final\_fit, }\AttributeTok{new\_data =}\NormalTok{ data)[}\StringTok{\textquotesingle{}.pred\textquotesingle{}}\NormalTok{]}

\NormalTok{data\_pred\_result[}\StringTok{\textquotesingle{}lasso\_pred\textquotesingle{}}\NormalTok{] }\OtherTok{\textless{}{-}} \FunctionTok{augment}\NormalTok{(lasso\_final\_fit, }\AttributeTok{new\_data =}\NormalTok{ data)[}\StringTok{\textquotesingle{}.pred\textquotesingle{}}\NormalTok{]}

\NormalTok{data\_pred\_result}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                              Country Population_2022 reg_tree_pred
## 1                        Afghanistan        41128771   40402614.62
## 2                            Albania         2842321    2047572.81
## 3                            Algeria        44903225   40402614.62
## 4                     American Samoa           44273      33204.59
## 5                            Andorra           79824     107999.00
## 6                             Angola        35588987   40402614.62
## 7                           Anguilla           15857      33204.59
## 8                Antigua and Barbuda           93763     107999.00
## 9                          Argentina        45510318   40402614.62
## 10                           Armenia         2780469    2047572.81
## 11                             Aruba          106445     107999.00
## 12                         Australia        26177413   26438580.29
## 13                           Austria         8939617   11014520.21
## 14                        Azerbaijan        10358074   11014520.21
## 15                           Bahamas          409984     669313.00
## 16                           Bahrain         1472233    2047572.81
## 17                        Bangladesh       171186372  552616606.43
## 18                          Barbados          281635     297079.57
## 19                           Belarus         9534954   11014520.21
## 20                           Belgium        11655930   11014520.21
## 21                            Belize          405272     669313.00
## 22                             Benin        13352864   11014520.21
## 23                           Bermuda           64184      33204.59
## 24                            Bhutan          782455     669313.00
## 25                           Bolivia        12224110   11014520.21
## 26            Bosnia and Herzegovina         3233526    4650272.88
## 27                          Botswana         2630296    2047572.81
## 28                            Brazil       215313498  552616606.43
## 29            British Virgin Islands           31305      33204.59
## 30                            Brunei          449002     669313.00
## 31                          Bulgaria         6781953    6921957.55
## 32                      Burkina Faso        22673762   26438580.29
## 33                           Burundi        12889576   11014520.21
## 34                          Cambodia        16767842   17810266.56
## 35                          Cameroon        27914536   26438580.29
## 36                            Canada        38454327   40402614.62
## 37                        Cape Verde          593149     669313.00
## 38                    Cayman Islands           68706      33204.59
## 39          Central African Republic         5579144    4650272.88
## 40                              Chad        17723315   17810266.56
## 41                             Chile        19603733   17810266.56
## 42                             China      1425887337  552616606.43
## 43                          Colombia        51874024   60374000.14
## 44                           Comoros          836774     669313.00
## 45                      Cook Islands           17011      33204.59
## 46                        Costa Rica         5180829    4650272.88
## 47                           Croatia         4030358    4650272.88
## 48                              Cuba        11212191   11014520.21
## 49                           Curacao          191163     297079.57
## 50                            Cyprus         1251488    2047572.81
## 51                    Czech Republic        10493986   11014520.21
## 52                           Denmark         5882261    6921957.55
## 53                          Djibouti         1120849     669313.00
## 54                          Dominica           72737     107999.00
## 55                Dominican Republic        11228821   11014520.21
## 56                          DR Congo        99010212   60374000.14
## 57                           Ecuador        18001000   17810266.56
## 58                             Egypt       110990103   97573131.57
## 59                       El Salvador         6336392    6921957.55
## 60                 Equatorial Guinea         1674908    2047572.81
## 61                           Eritrea         3684032    4650272.88
## 62                           Estonia         1326062    2047572.81
## 63                          Eswatini         1201670    2047572.81
## 64                          Ethiopia       123379924   97573131.57
## 65                  Falkland Islands            3780      33204.59
## 66                     Faroe Islands           53090      33204.59
## 67                              Fiji          929766     669313.00
## 68                           Finland         5540745    4650272.88
## 69                            France        64626628   60374000.14
## 70                     French Guiana          304557     297079.57
## 71                  French Polynesia          306279     297079.57
## 72                             Gabon         2388992    2047572.81
## 73                            Gambia         2705992    2047572.81
## 74                           Georgia         3744385    4650272.88
## 75                           Germany        83369843   97573131.57
## 76                             Ghana        33475870   40402614.62
## 77                         Gibraltar           32649      33204.59
## 78                            Greece        10384971   11014520.21
## 79                         Greenland           56466      33204.59
## 80                           Grenada          125438     107999.00
## 81                        Guadeloupe          395752     669313.00
## 82                              Guam          171774     107999.00
## 83                         Guatemala        17843908   17810266.56
## 84                          Guernsey           63301      33204.59
## 85                            Guinea        13859341   11014520.21
## 86                     Guinea-Bissau         2105566    2047572.81
## 87                            Guyana          808726     669313.00
## 88                             Haiti        11584996   11014520.21
## 89                          Honduras        10432860   11014520.21
## 90                         Hong Kong         7488865    6921957.55
## 91                           Hungary         9967308   11014520.21
## 92                           Iceland          372899     297079.57
## 93                             India      1417173173  552616606.43
## 94                         Indonesia       275501339  552616606.43
## 95                              Iran        88550570   97573131.57
## 96                              Iraq        44496122   40402614.62
## 97                           Ireland         5023109    4650272.88
## 98                       Isle of Man           84519     107999.00
## 99                            Israel         9038309    6921957.55
## 100                            Italy        59037474   60374000.14
## 101                      Ivory Coast        28160542   26438580.29
## 102                          Jamaica         2827377    2047572.81
## 103                            Japan       123951692  552616606.43
## 104                           Jersey          110778     107999.00
## 105                           Jordan        11285869   11014520.21
## 106                       Kazakhstan        19397998   17810266.56
## 107                            Kenya        54027487   60374000.14
## 108                         Kiribati          131232     107999.00
## 109                           Kuwait         4268873    4650272.88
## 110                       Kyrgyzstan         6630623    6921957.55
## 111                             Laos         7529475    6921957.55
## 112                           Latvia         1850651    2047572.81
## 113                          Lebanon         5489739    4650272.88
## 114                          Lesotho         2305825    2047572.81
## 115                          Liberia         5302681    4650272.88
## 116                            Libya         6812341    6921957.55
## 117                    Liechtenstein           39327      33204.59
## 118                        Lithuania         2750055    4650272.88
## 119                       Luxembourg          647599     669313.00
## 120                            Macau          695168     669313.00
## 121                       Madagascar        29611714   26438580.29
## 122                           Malawi        20405317   17810266.56
## 123                         Malaysia        33938221   40402614.62
## 124                         Maldives          523787     669313.00
## 125                             Mali        22593590   26438580.29
## 126                            Malta          533286     669313.00
## 127                 Marshall Islands           41569      33204.59
## 128                       Martinique          367507     297079.57
## 129                       Mauritania         4736139    4650272.88
## 130                        Mauritius         1299469    2047572.81
## 131                          Mayotte          326101     297079.57
## 132                           Mexico       127504125   97573131.57
## 133                       Micronesia          114164     107999.00
## 134                          Moldova         3272996    4650272.88
## 135                           Monaco           36469      33204.59
## 136                         Mongolia         3398366    4650272.88
## 137                       Montenegro          627082     669313.00
## 138                       Montserrat            4390      33204.59
## 139                          Morocco        37457971   40402614.62
## 140                       Mozambique        32969517   26438580.29
## 141                          Myanmar        54179306   60374000.14
## 142                          Namibia         2567012    2047572.81
## 143                            Nauru           12668      33204.59
## 144                            Nepal        30547580   26438580.29
## 145                      Netherlands        17564014   17810266.56
## 146                    New Caledonia          289950     297079.57
## 147                      New Zealand         5185288    4650272.88
## 148                        Nicaragua         6948392    6921957.55
## 149                            Niger        26207977   26438580.29
## 150                          Nigeria       218541212  552616606.43
## 151                             Niue            1934      33204.59
## 152                      North Korea        26069416   26438580.29
## 153                  North Macedonia         2093599    2047572.81
## 154         Northern Mariana Islands           49551      33204.59
## 155                           Norway         5434319    4650272.88
## 156                             Oman         4576298    4650272.88
## 157                         Pakistan       235824862  552616606.43
## 158                            Palau           18055      33204.59
## 159                        Palestine         5250072    4650272.88
## 160                           Panama         4408581    4650272.88
## 161                 Papua New Guinea        10142619   11014520.21
## 162                         Paraguay         6780744    6921957.55
## 163                             Peru        34049588   40402614.62
## 164                      Philippines       115559009   97573131.57
## 165                           Poland        39857145   40402614.62
## 166                         Portugal        10270865   11014520.21
## 167                      Puerto Rico         3252407    4650272.88
## 168                            Qatar         2695122    2047572.81
## 169            Republic of the Congo         5970424    6921957.55
## 170                          Reunion          974052     669313.00
## 171                          Romania        19659267   26438580.29
## 172                           Russia       144713314  552616606.43
## 173                           Rwanda        13776698   11014520.21
## 174                 Saint Barthelemy           10967      33204.59
## 175            Saint Kitts and Nevis           47657      33204.59
## 176                      Saint Lucia          179857     297079.57
## 177                     Saint Martin           31791      33204.59
## 178        Saint Pierre and Miquelon            5862      33204.59
## 179 Saint Vincent and the Grenadines          103948     107999.00
## 180                            Samoa          222382     297079.57
## 181                       San Marino           33660      33204.59
## 182            Sao Tome and Principe          227380     297079.57
## 183                     Saudi Arabia        36408820   40402614.62
## 184                          Senegal        17316449   17810266.56
## 185                           Serbia         7221365    6921957.55
## 186                       Seychelles          107118     107999.00
## 187                     Sierra Leone         8605718    6921957.55
## 188                        Singapore         5975689    6921957.55
## 189                     Sint Maarten           44175      33204.59
## 190                         Slovakia         5643453    4650272.88
## 191                         Slovenia         2119844    2047572.81
## 192                  Solomon Islands          724273     669313.00
## 193                          Somalia        17597511   17810266.56
## 194                     South Africa        59893885   60374000.14
## 195                      South Korea        51815810   60374000.14
## 196                      South Sudan        10913164   11014520.21
## 197                            Spain        47558630   40402614.62
## 198                        Sri Lanka        21832143   26438580.29
## 199                            Sudan        46874204   40402614.62
## 200                         Suriname          618040     669313.00
## 201                           Sweden        10549347   11014520.21
## 202                      Switzerland         8740472    6921957.55
## 203                            Syria        22125249   26438580.29
## 204                           Taiwan        23893394   26438580.29
## 205                       Tajikistan         9952787   11014520.21
## 206                         Tanzania        65497748   60374000.14
## 207                         Thailand        71697030   97573131.57
## 208                      Timor-Leste         1341296    2047572.81
## 209                             Togo         8848699    6921957.55
## 210                          Tokelau            1871      33204.59
## 211                            Tonga          106858     107999.00
## 212              Trinidad and Tobago         1531044    2047572.81
## 213                          Tunisia        12356117   11014520.21
## 214                           Turkey        85341241   97573131.57
## 215                     Turkmenistan         6430770    6921957.55
## 216         Turks and Caicos Islands           45703      33204.59
## 217                           Tuvalu           11312      33204.59
## 218                           Uganda        47249585   40402614.62
## 219                          Ukraine        39701739   40402614.62
## 220             United Arab Emirates         9441129   11014520.21
## 221                   United Kingdom        67508936   60374000.14
## 222                    United States       338289857  552616606.43
## 223     United States Virgin Islands           99465     107999.00
## 224                          Uruguay         3422794    4650272.88
## 225                       Uzbekistan        34627652   40402614.62
## 226                          Vanuatu          326740     297079.57
## 227                     Vatican City             510      33204.59
## 228                        Venezuela        28301696   40402614.62
## 229                          Vietnam        98186856   97573131.57
## 230                Wallis and Futuna           11572      33204.59
## 231                   Western Sahara          575986     669313.00
## 232                            Yemen        33696614   40402614.62
## 233                           Zambia        20017675   17810266.56
## 234                         Zimbabwe        16320537   17810266.56
##            rf_pred   ridge_pred lasso_pred
## 1     38079546.546   33653978.8   38445331
## 2      3053937.580    1560314.9    4279466
## 3     44676782.694   40195925.7   43327227
## 4        46830.535     678858.2    1472700
## 5        73600.113   -1890232.9    1500364
## 6     33467997.772   27387161.6   32908716
## 7        12013.162    1269247.6    1440237
## 8        91576.708    1350315.6    1516297
## 9     46737650.684   45093129.8   45600712
## 10     2986584.359    9087114.7    4237423
## 11      102813.037    1361215.6    1530262
## 12    41304142.454   16438192.5   26330428
## 13     9484748.683    7859662.6   10191079
## 14    10440602.438   15583538.6   11508562
## 15      414899.826    1633714.6    1824550
## 16     1461703.934    6594552.8    2855643
## 17   169756467.148  162094236.8  164670287
## 18      378779.189    1578701.5    1703208
## 19    10267344.883    9727227.7   11021609
## 20    11666211.700   10855352.0   12812947
## 21      388130.918    1557133.1    1806088
## 22    11574565.099   14299815.3   13429283
## 23       65488.358    1328349.7    1488442
## 24      799763.783    6179874.9    2183264
## 25    12571880.234   12703595.4   13010289
## 26     3429661.433    2669508.5    4790696
## 27     2564544.951    6208075.7    3876693
## 28   222577154.272  203410443.4  210683927
## 29       29716.992    1282083.0    1455309
## 30      454149.674    5875500.6    1857449
## 31     7714476.493    7529702.5    8469725
## 32    21067912.698   21146077.3   21895144
## 33    11923152.648   14254859.1   13080283
## 34    17385892.408   19981468.0   17399857
## 35    27223349.082   24844733.9   26611957
## 36    53540301.885   28130848.6   38373364
## 37      610524.759    5261159.5    1994156
## 38       60923.680    1307348.4    1489893
## 39     5495186.448    8756690.8    6563440
## 40    17252041.834   15476773.3   17145689
## 41    20298097.630   20997727.4   20137523
## 42  1270534248.827 1492284306.3 1407359304
## 43    50707389.042   49408670.6   50792309
## 44      744181.236    5393487.2    2201385
## 45       18651.138     642986.5    1442238
## 46     5323240.452    5964369.6    6441956
## 47     4893649.001    3363075.3    5548633
## 48    12149485.944   14190769.5   12669247
## 49      203871.704    1451207.7    1606751
## 50     1267057.317    -778742.1    2638539
## 51    11288261.547   10488385.8   11889019
## 52     6005911.005    4564846.8    7166437
## 53     1094860.274    5584592.4    2481023
## 54       77898.407    1339647.4    1495996
## 55    11272315.167   11576826.2   12162322
## 56    74502385.640   71314216.4   89049181
## 57    18059816.251   18560702.3   18448622
## 58   111503906.425   95519567.5  105033371
## 59     6602187.866    8025791.6    7658939
## 60     1493191.712    5776671.8    2929602
## 61     3360106.898    7783830.4    4888284
## 62     1540629.120    -328728.6    2741521
## 63     1241332.402    5843070.2    2583167
## 64   107668816.339   94510835.2  113065892
## 65        8451.420    3092810.3    1428708
## 66       51224.288   -1907070.1    1476007
## 67      984276.937    1588850.3    2338807
## 68     5743986.288    3957198.3    6904190
## 69    65836011.885   69516830.0   65289142
## 70      298580.446    3231426.7    1703138
## 71      357102.380     912169.5    1721836
## 72     2278865.286    6205995.3    3616932
## 73     2493826.072    6664807.4    3877984
## 74     4058906.010   10650200.2    5169590
## 75    96453905.083   95695807.4   83830170
## 76    33904297.142   30840713.7   32321780
## 77       34517.309   -1926214.1    1457541
## 78    10968865.106   10452047.7   11969376
## 79      172807.474   -1068753.1    1480734
## 80      122725.089    1388321.0    1546462
## 81      458330.313    1721986.3    1819438
## 82      198212.122     800749.6    1592876
## 83    17244826.021   16099864.9   18234332
## 84       65134.964   -1891191.7    1487121
## 85    12965981.706   15317384.2   14030912
## 86     2064597.269    6328379.4    3354078
## 87      884759.466    3784832.4    2203562
## 88    11454414.597   11655327.6   12418605
## 89    10214421.163    9680668.1   11213210
## 90     8079480.483   13286766.7    8846798
## 91    11230779.379   10208118.5   11146520
## 92      404367.035   -1720908.4    1777826
## 93  1270342537.219 1303366106.2 1365108361
## 94   222702251.841  263540801.6  267423896
## 95    86329875.561   82972135.4   86374431
## 96    43314205.092   38102400.6   42145754
## 97     5174601.549    2907344.0    6248830
## 98       86904.754   -1871637.7    1508476
## 99     9019295.987   13112261.9    9882764
## 100   62598068.052   67971805.1   60800545
## 101   28210420.441   25680277.6   27017127
## 102    2902920.242    4320473.7    4219679
## 103  157122523.745  154415553.6  126558958
## 104     108651.399   -1852908.6    1530203
## 105   10405684.069   12927255.9   11815942
## 106   20282643.735   22260474.4   19912560
## 107   49001247.081   45575662.4   51406662
## 108     120065.134     736245.8    1547580
## 109    4082365.397    8669314.0    5610523
## 110    6490261.469   11364096.2    7643176
## 111    7143278.165   11834523.7    8524959
## 112    2124579.335     696575.8    3341640
## 113    5679401.858   10999467.5    7294774
## 114    2349903.964    6944170.5    3620858
## 115    5221612.260    8704566.3    6325467
## 116    7134819.936    8951460.5    7886651
## 117      39767.618   -1923255.8    1463154
## 118    3176413.138    1916219.7    4275132
## 119     627599.900   -1385772.2    2031607
## 120     682194.009    6055907.8    2077192
## 121   28775372.041   26184583.0   28369583
## 122   17826192.751   19956082.7   19883027
## 123   34914493.533   34088072.9   33721792
## 124     518780.008    5872945.3    1910496
## 125   21233913.546   19759822.9   21497799
## 126     564560.978   -1464067.2    1917998
## 127      44505.670     676101.1    1470210
## 128     435603.431    1711752.4    1797518
## 129    4237815.465    7141770.7    5714793
## 130    1412674.077    6122168.9    2713418
## 131     288862.596    4919136.0    1710414
## 132  129813076.877  118379105.5  124730245
## 133     112429.684     741978.1    1535645
## 134    3409430.875    2547731.1    4554181
## 135      38727.499   -1923306.5    1461737
## 136    3366502.920    6761290.7    4591037
## 137     723340.712   -1231870.6    2051894
## 138       6901.890    1263998.5    1429751
## 139   40718019.101   39030914.8   37229457
## 140   32572977.949   28302414.5   30989227
## 141   56031749.761   58749613.4   53883764
## 142    2557958.112    5971030.4    3831173
## 143      11371.883     634222.3    1436964
## 144   31686919.904   33704668.6   30023005
## 145   19062961.986   17211855.9   18623450
## 146     320646.588     873275.6    1708633
## 147    5246549.980    5197227.9    6300725
## 148    6689676.184    7318981.4    7989425
## 149   24764367.617   20634390.5   24229157
## 150  198412374.368  170735044.9  200488064
## 151       5291.447     624878.2    1426994
## 152   29211632.158   32649262.8   26933680
## 153    2202945.563     455809.2    3522180
## 154      51397.825     678921.9    1475010
## 155    5540413.273    3360125.1    6709709
## 156    4324147.862    8441258.9    5825197
## 157  204074578.882  198063808.8  221901041
## 158      17414.581     641737.0    1442899
## 159    5127602.435    9468852.3    6238167
## 160    4248907.771    4981079.7    5582425
## 161   10071038.078    7761909.3   10764544
## 162    6632100.869    8728920.5    7858499
## 163   36849897.829   33097104.0   33674385
## 164  115560766.843  103418131.9  109921091
## 165   44116353.818   43156538.0   39658381
## 166   10482094.085   10177586.4   11682102
## 167    3366025.857    5416734.4    4750656
## 168    2106991.334    7113657.1    4055041
## 169    5703700.264    8800707.7    6882944
## 170     984091.503    5651005.3    2365441
## 171   26683392.226   23034365.0   20900003
## 172  176762553.745  152694104.8  145836622
## 173   12498441.793   15662978.4   13997342
## 174      10377.316    1264284.1    1435370
## 175      48297.783    1310550.4    1472493
## 176     204029.353    1442888.0    1602045
## 177      34070.254    1288177.9    1458257
## 178       7562.851    1262578.0    1430989
## 179     116556.376    1385800.9    1529692
## 180     251513.939     844328.3    1634977
## 181      34842.695   -1928639.6    1458750
## 182     210616.892    4897751.7    1636645
## 183   36151379.908   31699020.0   36135457
## 184   17079560.477   17600197.1   17077692
## 185    8205520.485    7195120.3    8790903
## 186     104416.472    4809623.5    1527913
## 187    8286095.289   11432943.9    9306839
## 188    5784230.779   10687259.1    7213391
## 189      39942.167    1291650.4    1467327
## 190    5760891.122    4352346.3    6837682
## 191    2210976.554     441479.9    3517660
## 192     678753.853    1148886.5    2086270
## 193   17362641.101   16596649.8   16950492
## 194   59788338.374   58880380.7   58905825
## 195   55965446.539   61016096.4   52672314
## 196   11133344.981   13298017.7   12159165
## 197   48665638.348   48972666.7   48191985
## 198   26017932.152   28105667.1   22882626
## 199   45289232.007   38145468.8   43535234
## 200     647035.787    3525125.8    2018065
## 201   10790367.902    8675723.2   11559854
## 202    9043135.878    7036005.8    9893532
## 203   23876198.469   24886351.4   21555727
## 204   28527370.050   31408546.5   24998735
## 205    9902525.790   13479297.9   10575236
## 206   58983697.823   50891499.3   59744039
## 207   71294538.752   78588366.3   72074097
## 208    1280730.420    6633502.5    2686198
## 209    8574519.378   11412884.2    9497710
## 210       3877.291     624036.2    1426789
## 211     111791.488     744476.5    1529988
## 212    1567159.110    2863674.9    2914894
## 213   12352543.859   16236664.7   13313925
## 214   84087359.240   83587177.3   83570527
## 215    6111965.724   10547734.2    7478307
## 216      31057.465    1284027.7    1466560
## 217      11187.172     633667.7    1436033
## 218   44771553.004   37977982.6   43283662
## 219   46405537.705   54552637.2   45417157
## 220    9352555.807   11896358.5   10533791
## 221   68122057.825   71908290.1   67470460
## 222  231627522.663  334924372.2  331584184
## 223     111216.391    1374841.4    1525695
## 224    3435683.804    6820794.8    4824499
## 225   35228873.029   35409152.1   33900059
## 226     304476.594     864290.6    1723299
## 227       3810.837   -1961733.7    1425627
## 228   34514017.540   31004877.6   30409781
## 229  104155616.273   98774170.8   96017416
## 230      12539.047     636979.5    1436852
## 231     532450.705    4815244.5    1956652
## 232   33645910.180   29942850.4   32274475
## 233   17931746.379   18188961.6   19357232
## 234   17282298.656   18326011.5   16501431
\end{verbatim}

From the Table, In many countries, the model predictions are quite
different from the actual values. For example, the actual value of
American Samoa's population is 44273, but its Lasso Regression
prediction result is 1507434; the actual population value of Anguilla is
15857, but its Lasso Regression prediction result is 1476729. These
predictions are much larger than actual values, so the predictions are
not accurate.

Advantage of lasso model: the value of its metric r squared value is the
highest and closest to the actual value among the four models. In the
other three models, there are negative numbers in the prediction
results, but Lasso model's predict result stays positive in all its
predicted values.

\hypertarget{conclusion}{%
\subsection{Conclusion}\label{conclusion}}

Through research, testing and analysis, Lasso Regression performed best
in my models, Ridge Regression and Random forest are not bad, and
Regression Tree did not perform well. Although the value of the r
squared value of Lasso Regression, Random Forest and Ridge Regression is
very close to 1, there is still a gap between the prediction results of
many countries and their real population values. Because a lot of
factors such as people's life expectancy, fertility rate and death rate
are all related to population growth, there is no way to predict the
exact future world population.

In addition, the regression models has its limitation that it predicts a
similar pattern for each continents or level of size of countries.
However, from EDA at the beginning, even in the same continent or shares
the similar value of areas, the country's growth rate differs.
Therefore, for future research I propose to find more features to
improve our model, such that gross national happiness index, and GDP,
etc. We can also try more complicated models such as neuro network
model.

Overall, this World Population Modeling project provided me with a great
opportunity to gain experience and improve my skills through data
analysis and machine learning techniques.

\end{document}
